// Per-fork branding. Everything project-specific that a new translation
// workbench must change lives here, so a fork is a one-file edit rather than a
// hunt through the React tree. Deployment/runtime config (which repo to read,
// the custom domain, secrets) stays in `wrangler.jsonc` and Worker secrets.

export const SITE = {
  // This workbench's own name. Shows in the browser title and the header.
  appName: 'Grimoire Translate',
  // Short badge shown in the header mark (2-3 letters).
  shortName: 'GT',
  // Public URL of this workbench. Referenced in the PR descriptions it opens.
  url: 'https://translate.grimoiremods.com',
  // The end-user application whose strings you are translating. Used in UI copy
  // like "...words that repeat across Grimoire" and "enter Translation Mode in
  // Grimoire".
  clientName: 'Grimoire',
  // Brand/product nouns that usually should NOT be translated. The glossary
  // helper surfaces these first so translators agree on (or skip) them up front.
  // Purely domain content — replace with your own project's terms.
  priorityGlossaryTerms: [
    'Grimoire',
    'Deadlock',
    'Deadworks',
    'GameBanana',
    'Steam',
    'Discord',
    'Statlocker',
    'mod',
    'mods',
    'mod manager',
    'profile',
    'profiles',
    'portable profile',
    'share code',
    'game path',
    'addon',
    'addons',
    'VPK',
    'GLB',
    'gameinfo.gi',
    '.vpk',
    '.glb',
    '.modprofile.json',
    'mp1:',
    'autoexec',
    'autoexec.cfg',
    'crosshair',
    'locker',
    'Locker',
    'Browse',
    'Discover',
    'Installed',
    'Conflicts',
    'server',
    'servers',
    'relay',
    'download',
    'import',
    'export',
    'publish',
    'snapshot',
    'restore',
    'update',
    'variant',
    'variants',
    'merge',
    'unmerge',
    'load order',
    'override',
    'overrides',
    'cache',
    'NSFW',
    'hero',
    'heroes',
    'hero card',
    'ability',
    'abilities',
    'soul container',
    'skin',
    'skins',
    'VFX',
    'HUD',
    'UI',
    'FPS',
    'ADS',
    'MMR',
    'replay key',
    'match key',
    'Launch Modded',
  ],
} as const;
